// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// DatasetsUrlResponse defines model for DatasetsUrlResponse.
type DatasetsUrlResponse struct {
	// Expires The earliest expiration of all urls for this dataset
	Expires time.Time `json:"expires"`
	Urls    []UrlInfo `json:"urls"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message describing the issue with the request or server
	Error string `json:"error"`
}

// PublishedDataUrlsResponse defines model for PublishedDataUrlsResponse.
type PublishedDataUrlsResponse struct {
	// Expires The earliest expiration of all datasets' urls
	Expires time.Time                      `json:"expires"`
	Urls    map[string]DatasetsUrlResponse `json:"urls"`
}

// S3CredentialsResponse defines model for S3CredentialsResponse.
type S3CredentialsResponse struct {
	// AccessKey The temporary AWS access key ID
	AccessKey string `json:"access_key"`

	// ExpiryTime The expiration time of the credentials in RFC 3339 format
	ExpiryTime time.Time `json:"expiry_time"`

	// SecretAccessKey The temporary AWS secret access key
	SecretAccessKey string `json:"secret_access_key"`

	// SessionToken The temporary AWS session token
	SessionToken string `json:"session_token"`
}

// UrlInfo defines model for UrlInfo.
type UrlInfo struct {
	// Expires The expiration time of the URL in RFC 3339 format
	Expires time.Time `json:"expires"`

	// Url The URL to access the dataset
	Url string `json:"url"`
}

// GetDatasetsS3CredsParams defines parameters for GetDatasetsS3Creds.
type GetDatasetsS3CredsParams struct {
	// Pid The unique identifier of the dataset
	Pid string `form:"pid" json:"pid"`
}

// GetDatasetsUrlsParams defines parameters for GetDatasetsUrls.
type GetDatasetsUrlsParams struct {
	// Pid The unique identifier of the dataset
	Pid string `form:"pid" json:"pid"`
}

// GetPublisheddataUrlsParams defines parameters for GetPublisheddataUrls.
type GetPublisheddataUrlsParams struct {
	// Id The id or doi of the published data
	Id string `form:"id" json:"id"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get temporary S3 credentials for a dataset
	// (GET /datasets/s3-creds)
	GetDatasetsS3Creds(c *gin.Context, params GetDatasetsS3CredsParams)
	// Get download URLs for a dataset
	// (GET /datasets/urls)
	GetDatasetsUrls(c *gin.Context, params GetDatasetsUrlsParams)
	// Get download URLs for a published data
	// (GET /publisheddata/urls)
	GetPublisheddataUrls(c *gin.Context, params GetPublisheddataUrlsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetDatasetsS3Creds operation middleware
func (siw *ServerInterfaceWrapper) GetDatasetsS3Creds(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDatasetsS3CredsParams

	// ------------- Required query parameter "pid" -------------

	if paramValue := c.Query("pid"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pid is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "pid", c.Request.URL.Query(), &params.Pid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pid: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDatasetsS3Creds(c, params)
}

// GetDatasetsUrls operation middleware
func (siw *ServerInterfaceWrapper) GetDatasetsUrls(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDatasetsUrlsParams

	// ------------- Required query parameter "pid" -------------

	if paramValue := c.Query("pid"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pid is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "pid", c.Request.URL.Query(), &params.Pid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pid: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDatasetsUrls(c, params)
}

// GetPublisheddataUrls operation middleware
func (siw *ServerInterfaceWrapper) GetPublisheddataUrls(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublisheddataUrlsParams

	// ------------- Required query parameter "id" -------------

	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "id", c.Request.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublisheddataUrls(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/datasets/s3-creds", wrapper.GetDatasetsS3Creds)
	router.GET(options.BaseURL+"/datasets/urls", wrapper.GetDatasetsUrls)
	router.GET(options.BaseURL+"/publisheddata/urls", wrapper.GetPublisheddataUrls)
}
